### ISSUE TITLE
Point of project

### ISSUE THREAD

**Issue by KeizerDev** [borzecki/q#2]
What's the actual difference between [S](https://github.com/zquestz/s) and `q`?

**Comment by borzecki** [comment]
There's not that much to it right now. I like the idea of launching search engines directly from terminal and also wanted to write some piece of code that could be easily distributed.

I have few ideas to further enhance it to something of more general use, but I know that it's purely educational purpose may seem pointless to others.

**Comment by KeizerDev** [comment]
No, not at all for my. I like the idea of recreating stuff just for educational purposes but thought there was maybe some enhancements you planned to do to move it in a different direction.
